### ISSUE TITLE
Gradient support

### ISSUE THREAD

**Issue by tchayen** [sammycage/plutosvg#14]
Hi! I am trying to render Noto color emoji font. I thought I might have messed up something in my config, but then I checked the `emoji2png` example and I am noticing the same issues.

This is reference emoji:

![Screenshot 2024-08-24 at 12 32 59](https://github.com/user-attachments/assets/1a8a26ab-f8c0-4ad7-9616-ad9ba8983055)

And this is after rendering with `emoji2png` ([this](https://fonts.google.com/noto/specimen/Noto+Color+Emoji) font, character 0x1F973):

![emoji-1f973](https://github.com/user-attachments/assets/262992e0-637b-4603-a770-7b8156071ae9)

_If this helps, the original SVG file from the repo is [here](https://github.com/googlefonts/noto-emoji/blob/main/svg/emoji_u1f973.svg)._

I guess this means that either `plutovg` or `plutosvg` don't support the kind of gradient used here. Is this something you would consider looking into? Or should I use `lunasvg` for this?

**Comment by sammycage** [comment]
@tchayen Thank you for bringing this to my attention! I appreciate you sharing the reference and the original SVG file. I'll definitely investigate this issue to see if it's related to gradient support in `plutovg` or `plutosvg`. I'll keep you updated on any findings.

**Comment by sammycage** [comment]
@tchayen I've fixed this issue in the latest update. If you're using it for rendering OpenType-SVG fonts, PlutoSVG is a great choice.

**Comment by tchayen** [comment]
Thank you so much for fixing this issue so quickly! I just checked and my problem is gone.

I am using PlutoSVG for OT SVG support and indeed I am very happy with it! Thank you for this great library!
