### ISSUE TITLE
Does plutosvg support styles?

### ISSUE THREAD

**Issue by pthom** [sammycage/plutosvg#16]
Hello Samuel,

I found that the ellipse in the svg renders in black instead of the specified color (#ffda6b in the .st1 style class):

```xml
<?xml version="1.0" encoding="utf-8"?>
<svg width="800px" height="800px" viewBox="0 0 100 100" id="Layer_1" xmlns="http://www.w3.org/2000/svg">
<style>
    .st1{fill:#ffda6b}
</style>

<ellipse class="st1" cx="50" cy="50" rx="50" ry="50"/>
</svg>
```

Is this a known limitation of plutosvg, or is there an alternative syntax that works better with the library?

Note:

```xml
<ellipse fill="#ffda6b" cx="50" cy="50" rx="50" ry="50"/>
```

would work of course

**Comment by sammycage** [comment]
Yes, plutosvg is based on [SVG OpenType](https://docs.microsoft.com/en-us/typography/opentype/spec/svg), which unfortunately doesn't support stylesheets.
