### ISSUE TITLE
Images not always rendered

### ISSUE THREAD

**Issue by th-otto** [sammycage/plutosvg#18]
With same example as in https://github.com/sammycage/plutovg/issues/43:

![clock](https://github.com/user-attachments/assets/6e6bbc2e-ae9d-4936-bdd6-434a723e744e)

Some of the circles are not rendered:

![clock svg](https://github.com/user-attachments/assets/94be307d-e42b-4d82-ac9e-c7f8f554bec1)

The hand and the text isn't rendered either. This is independent on the bigendian patch and also happens on linux.

**Comment by sammycage** [comment]
Hi,

I reviewed the attached file and compared the rendering in Chrome and PlutoSVG on Linux. However, I'm unable to observe any noticeable differences between the two when the image is rendered. This is the output image when rendered with the `plutosvg svg2png` program:

![hello](https://github.com/user-attachments/assets/f65ad7f1-a29f-4365-8a10-47181037cdc8)

**Comment by th-otto** [comment]
The generate camera.png looks ok to me:

![camera](https://github.com/user-attachments/assets/e82c206c-910d-4ecb-a311-f0d7d851d33b)

**Comment by sammycage** [comment]
My bad! I just realized I was using the old SVG file from https://github.com/sammycage/plutovg/issues/43. That was my oversight, and I appreciate your patience.  

After testing with the current file, I noticed it uses text tags, which are not supported by PlutoSVG.

**Comment by th-otto** [comment]
Oops. Whats the difference? The SVG files i attached are identical.

**Comment by sammycage** [comment]
My bad again ;). I just noticed that I removed all the image tags in the original SVG file when fixing the Endianness problems in https://github.com/sammycage/plutovg/issues/43.

**Comment by sammycage** [comment]
Phew 😅 Thanks for reporting this issue! It has been fixed with the latest commit. Test it out and let me know your feedback!

**Comment by th-otto** [comment]
Yes, perfect, thank you for this quick fix!
