### ISSUE TITLE
svgtoPng stdcall dll

### ISSUE THREAD

**Issue by xiaoyaocode163** [sammycage/plutosvg#20]
Convert SVG files to PNG image files
Some additional features can be added:
1. Take the effective image area of SVG and return Rett (left, top, width, height). For example, if the image is 500 * 400, the actual area with data is 450 * 320 (areas with blank space around can be cut off)
2. Convert SVG in memory to PNG or transparent bitmap objects, which can be drawn using the GDI32 API (pass in SVG memory address and length, return PNG image memory address and length) (svgtopng(svg_BYTE_PTR,LEN1,Pngwidth,pngheight,drawx,drawy,Return_PNG_PTR,PNGlength)
4. It would be even better if it could support reading layers of all elements, such as marking or exporting N PNG files;
Then each element can be controlled by code to modify its color, making it a GIF animation that is also good for making small games.
5. Compile static libraries and generate 32-bit and 64 bit DLLs for VB6, VBA (STDcall convention)
6. Develop an interface similar to GIF animation that can display SVG animation directly on the window without the need for a webpage

**Comment by sammycage** [comment]
Thanks for the suggestions! They’re really great ideas, but they’re a bit out of scope for this library and honestly quite a lot of work. That said, I’m currently looking for work, so if you’re interested, I’d be happy to take this on as a freelance project. Just drop me an email at sammycageagle@gmail.com, and we can discuss it further!
