### ISSUE TITLE
no install command cmake scripts

### ISSUE THREAD

**Issue by steprun** [sammycage/plutosvg#4]
no install command cmake scripts, could add it?

**Comment by Shumpert820** [comment]
> no install command cmake scripts, could add it?

see README.md

**Comment by sammycage** [comment]
> no install command cmake scripts, could add it?

@Shumpert820 maybe he is referring to ``make install``

**Comment by sammycage** [comment]
To install the project on your system, follow these steps:

git clone https://github.com/sammycage/plutosvg.git
cd plutovg
meson setup build
ninja -C build
ninja -C build install

This will clone the repository, set up the build environment, and install the project.
