### ISSUE TITLE
declaration of "id" hides function parameter

### ISSUE THREAD

**Issue by moudey** [sammycage/plutosvg#6]
Hello @sammycage,

I found this alert during the compile

declaration of "id" hides function parameter
https://github.com/sammycage/plutosvg/blob/336c02997277a1888e6ccbbbe674551a0582e5c4/source/plutosvg.c#L520

declaration of 'value' hides previous local declaration
https://github.com/sammycage/plutosvg/blob/336c02997277a1888e6ccbbbe674551a0582e5c4/source/plutosvg.c#L1212

Thanks

**Comment by sammycage** [comment]
It is just a warning.. I will try to fix it away.. <3😎
