### ISSUE TITLE
The build script doesn't work

### ISSUE THREAD

**Issue by logos-maker** [sammycage/plutosvg#8]
Why does it require a version that doesn't exist yet?

cmake_minimum_required(VERSION 3.3)

And then following the instruction I get the message...
CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory  does not contain a CMakeLists.txt file.

**Comment by sammycage** [comment]
**git clone --recursive https://github.com/sammycage/plutosvg.git**
cd plutosvg
mkdir build
cd build
cmake ..
make

**Comment by logos-maker** [comment]
Thanks! 
The --recursive flag is important :-) It's not that common so I missed that.

**Comment by logos-maker** [comment]
But the library still doesn't get installed to my system. How do I install it?
fatal error: plutosvg.h: No such file or directory
    1 | #include <plutosvg.h>
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by sammycage** [comment]
@logos-maker Thank you for bringing this to my attention. I'll work on adding a CMake install script to ensure the library gets installed properly on your system. I'll update you once it's done.
